version: "3.8"
services:
  db: # db 서비스
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306" # TCP 포트 : 데이터베이스 연결 포트
    env_file:
      - mariadb.env

  app: # spring app 서비스
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # HTTP 포트 연결
    depends_on: # app 서비스 시작 전 실행되어야 하는 서비스
      - db
    restart: always # depends on은 실행 순서만 컨트롤 할뿐,
    # 컨테이너 안의 서비스가 실행가능한 상태인지까지는 확인 하지 않기 때문에
    # DB가 아직 실행가능한 상태가 아니여서 실패하는 경우 재시작 하도록 설정
    env_file:
      - app.env